name: docs
on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: write

jobs:
    docs:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        - name: Install dependencies	
          run: |	
            python -m pip install --upgrade pip	
            pip install mkdocs	
        - name: Update docs	
          run: |	
            mkdocs build	
            mkdocs gh-deploy --force
